#!/usr/bin/env -S node --import tsx

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { LLParse } from "llparse";

const kComplete = 1;
const kHeaderDone = 2;
const kInvalid = 3;
const prefix = "fiber_http1_header_line";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const sourcePath = resolve(scriptDir, "../../src/http/generated/Http1HeaderLineParser.cpp");
const headerPath = resolve(scriptDir, "../../src/http/generated/Http1HeaderLineParser.h");

function buildGraph() {
    const parser = new LLParse(prefix);
    const lineStart = parser.node("line_start");
    const headerEnd = parser.node("header_end");
    const name = parser.node("name");
    const afterName = parser.node("after_name");
    const nameDelimiter = parser.node("name_delimiter");
    const afterEmptyValue = parser.node("after_empty_value");
    const beforeValue = parser.node("before_value");
    const value = parser.node("value");
    const afterValue = parser.node("after_value");
    const almostDone = parser.node("almost_done");
    const headerAlmostDone = parser.node("header_almost_done");
    const complete = parser.pause(kComplete, "Header line complete");
    const headersComplete = parser.pause(kHeaderDone, "Header block complete");
    const invalid = parser.error(kInvalid, "Invalid header line character");

    const nameBytes: number[] = [];
    for (let byte = 0x21; byte <= 0xff; ++byte) {
        if (byte !== ":".charCodeAt(0) && byte !== 0x7f) {
            nameBytes.push(byte);
        }
    }

    const valueBytes: number[] = [];
    const valueStartBytes: number[] = [];
    for (let byte = 1; byte <= 0xff; ++byte) {
        if (byte !== "\r".charCodeAt(0) && byte !== "\n".charCodeAt(0)) {
            valueBytes.push(byte);
            if (byte !== " ".charCodeAt(0)) {
                valueStartBytes.push(byte);
            }
        }
    }

    const nameSpan = parser.span(parser.code.span(`${prefix}_on_name`));
    const valueSpan = parser.span(parser.code.span(`${prefix}_on_value`));
    const onNameEnd = parser.invoke(parser.code.match(`${prefix}_on_name_end`), nameDelimiter);
    const onEmptyValue = parser.invoke(parser.code.match(`${prefix}_on_empty_value`), afterEmptyValue);
    const onHeaderEnd = parser.invoke(parser.code.match(`${prefix}_on_header_end`), headerEnd);

    lineStart
        .peek(["\r", "\n"], onHeaderEnd)
        .peek(nameBytes, nameSpan.start(name))
        .otherwise(invalid);

    headerEnd
        .match("\r", headerAlmostDone)
        .match("\n", headersComplete)
        .otherwise(invalid);

    // These self-loops are intentionally explicit. LLParse recognizes them and
    // emits a lookup-table loop plus target-specific SIMD scans where available.
    name.match(nameBytes, name).otherwise(nameSpan.end(afterName));

    afterName
        .peek([":", "\r", "\n"], onNameEnd)
        .otherwise(invalid);

    nameDelimiter
        .match(":", beforeValue)
        .peek(["\r", "\n"], onEmptyValue)
        .otherwise(invalid);

    beforeValue
        .match(" ", beforeValue)
        .peek(["\r", "\n"], onEmptyValue)
        .peek(valueStartBytes, valueSpan.start(value))
        .otherwise(invalid);

    afterEmptyValue
        .match("\r", almostDone)
        .match("\n", complete)
        .otherwise(invalid);

    value.match(valueBytes, value).otherwise(valueSpan.end(afterValue));

    afterValue
        .match("\r", almostDone)
        .match("\n", complete)
        .otherwise(invalid);

    almostDone.match("\n", complete).otherwise(invalid);
    headerAlmostDone.match("\n", headersComplete).otherwise(invalid);

    // HeaderLineParser reinitializes after either pause. LLParse nevertheless
    // requires resumable pause edges in the graph.
    complete.otherwise(lineStart);
    headersComplete.otherwise(lineStart);

    return parser.build(lineStart, {
        c: {
            header: "Http1HeaderLineParser",
        },
        headerGuard: "FIBER_HTTP_GENERATED_HTTP1_HEADER_LINE_PARSER_H",
    });
}

function generatedFiles(): ReadonlyArray<readonly [string, string]> {
    const artifacts = buildGraph();
    const notice = "// Generated by scripts/http/generate_header_line_parser.ts. Do not edit.\n";
    const statusEnum = `
enum fiber_http1_header_line_status {
  FIBER_HTTP1_HEADER_LINE_COMPLETE = ${kComplete},
  FIBER_HTTP1_HEADER_LINE_HEADERS_COMPLETE = ${kHeaderDone},
  FIBER_HTTP1_HEADER_LINE_INVALID = ${kInvalid}
};
typedef enum fiber_http1_header_line_status fiber_http1_header_line_status_t;
`;
    const spanCallbackField = "  void* _span_cb0;";
    if (!artifacts.header.includes(spanCallbackField)) {
        throw new Error("LLParse header no longer contains the expected shared span callback field");
    }
    const header = artifacts.header.replace(
        spanCallbackField,
        `  int (*_span_cb0)(struct ${prefix}_s*, const unsigned char*, const unsigned char*);`,
    ).replace(
        "\n#ifdef __cplusplus\n}  /* extern \"C\" */",
        `${statusEnum}\n#ifdef __cplusplus\n}  /* extern "C" */`,
    );

    const spanCallbackType =
        `             ${prefix}_t*, const char*, const char*);`;
    const spanCallbackCall =
        `    error = ((${prefix}__span_cb) state->_span_cb0)(state, state->_span_pos0, (const char*) endp);`;
    if (!artifacts.c.includes(spanCallbackType) ||
        !artifacts.c.includes("    start = state->_span_pos0;") ||
        !artifacts.c.includes(spanCallbackCall)) {
        throw new Error("LLParse C output no longer matches the expected span ABI");
    }
    const source = artifacts.c
        .replace(
            spanCallbackType,
            `             ${prefix}_t*, const unsigned char*, const unsigned char*);`,
        )
        .replaceAll(
            "    start = state->_span_pos0;",
            "    start = static_cast<const unsigned char*>(state->_span_pos0);",
        )
        .replace(
            spanCallbackCall,
            `    error = ((${prefix}__span_cb) state->_span_cb0)(state, ` +
                "static_cast<const unsigned char*>(state->_span_pos0), " +
                "reinterpret_cast<const unsigned char*>(endp));",
        );
    return [
        [headerPath, `${notice}// clang-format off\n${header}// clang-format on\n`],
        [sourcePath, `${notice}// clang-format off\n${source}\n// clang-format on\n`],
    ];
}

let failed = false;
for (const [path, generated] of generatedFiles()) {
    if (process.argv.includes("--check")) {
        let current = "";
        try {
            current = readFileSync(path, "utf8");
        } catch {
            console.error(`missing generated file: ${path}`);
            failed = true;
            continue;
        }
        if (current !== generated) {
            console.error(`generated file is stale: ${path}`);
            failed = true;
        }
    } else {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, generated);
    }
}

if (failed) {
    process.exitCode = 1;
}
