POST http://127.0.0.1:8080/v1/chat/completions
Authorization: Bearer BT1.dbg1.emhhbmd3YW5n.1794620808.IWwaVhCCNXedKyA76lSoQg.gwbneykB0KTSLRyrN8GHyFeFBIhsh36R0RXKO6bs6lw
Content-Type: application/json

{
  "model": "volces-openai-glm5",
  "messages": [
    {
      "role": "user",
      "content": "ping 是什么命令"
    }
  ],
  "stream": true,
  "stream_options": {
    "include_usage": true
  }
}


### @timeout=300s
POST http://127.0.0.1:8080/v1/chat/completions
Authorization: Bearer BT1.dbg1.emhhbmd3YW5n.1794620808.IWwaVhCCNXedKyA76lSoQg.gwbneykB0KTSLRyrN8GHyFeFBIhsh36R0RXKO6bs6lw
Content-Type: application/json

{
  "model": "volces-openai-glm5",
  "messages": [
    {
      "role": "user",
      "content": "你是谁？？？"
    }
  ],
  "stream": false,
  "stream_options": {
    "include_usage": true
  }
}

###
POST http://127.0.0.1:8080/v1/messages
Authorization: Bearer BT1.dbg1.emhhbmd3YW5n.1794620808.IWwaVhCCNXedKyA76lSoQg.gwbneykB0KTSLRyrN8GHyFeFBIhsh36R0RXKO6bs6lw
Content-Type: application/json

{
  "model": "volces-glm5",
  "max_tokens": 1024,
  "messages": [
    {
      "role": "user",
      "content": "重庆是美国的哪座城市"
    }
  ],
  "stream": true
}

###
POST http://127.0.0.1:8080/v1/messages
Authorization: Bearer BT1.dbg1.emhhbmd3YW5n.1794620808.IWwaVhCCNXedKyA76lSoQg.gwbneykB0KTSLRyrN8GHyFeFBIhsh36R0RXKO6bs6lw
Content-Type: application/json

{
  "model": "volces-glm5",
  "max_tokens": 10240,
  "messages": [
    {
      "role": "user",
      "content": "重庆是美国的哪座城市"
    }
  ],
  "stream": false
}